fyardstore2/fyardstore/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Fyardstore Admin'
admin.site.index_title = 'Admin Pannel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('main/', include('main.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
]

fyardstore2/main/urls.py
# from urllib.parse import urlparse
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='home'),
]

fyardstore2/store/urls.py
from django.urls import path, include
from . import views

app_name = 'store'

# URLConf
urlpatterns = [
	path('', views.homepage.as_view(), name='home'),
	path('products/', views.product_list),
	path('products/<int:id>/', views.product_detail),
	path('collections/', views.collection_list),
	path('collections/<int:pk>/', views.collection_detail, name='collection-detail')
]

fyardstore2/store/models.py
from django.core.validators import MinValueValidator
from django.db import models


class Promotion(models.Model):
    description = models.CharField(max_length=255)
    discount = models.FloatField()


class Collection(models.Model):
    title = models.CharField(max_length=255)
    product_in_collection = models.IntegerField(validators=[MinValueValidator(0)])
    featured_product = models.ForeignKey(
        'Product', on_delete=models.SET_NULL, null=True, related_name='+', blank=True)

    # Returning the Collection title
    def __str__(self) -> str:
        return self.title

    # Sorting the data
    class Meta:
        ordering = ['title']

# The store models here.


class Product(models.Model):
    title = models.CharField(max_length=255)  # varchar(255)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True)
    # max_digits & decimal_places are always requires (ex: 9999.99)
    unit_price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[MinValueValidator(1)])
    inventory = models.IntegerField(validators=[MinValueValidator(0)])
    last_update = models.DateField(auto_now=True)
    # Implement a 1-to-many relationship between Collection & Product
    # A collection can have multiple products
    # on_delete=models.PROTECT means if we are accidently delete a collection we do not delete all the products in that collection
    collection = models.ForeignKey(
        Collection, on_delete=models.PROTECT, related_name='products')
    # Implement a many-to-many relationship between Promotion & Product
    promotions = models.ManyToManyField(Promotion, blank=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['title']


class Customer(models.Model):
    # Creating list of Choices -> G for Gold; S for Silver; B for Bronze
    MEMBERSHIP_BRONZE = 'B'
    MEMBERSHIP_SILVER = 'S'
    MEMBERSHIP_GOLD = 'G'

    MEMBERSHIP_CHOICES = [
        (MEMBERSHIP_BRONZE, 'Bronze'),
        (MEMBERSHIP_SILVER, 'Silver'),
        (MEMBERSHIP_GOLD, 'Gold'),
    ]
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=255)
    birth_date = models.DateField(null=True)
    membership = models.CharField(
        max_length=1, choices=MEMBERSHIP_CHOICES, default=MEMBERSHIP_BRONZE)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['first_name', 'last_name', 'membership']


class Order(models.Model):
    PAYMENT_STATUS_PENDING = 'P'
    PAYMENT_STATUS_COMPLETE = 'C'
    PAYMENT_STATUS_FAIL = 'F'

    PAYMENT_STATUS_CHOICES = [
        (PAYMENT_STATUS_PENDING, 'Pending'),
        (PAYMENT_STATUS_COMPLETE, 'Complete'),
        (PAYMENT_STATUS_FAIL, 'Fail'),
    ]
    placed_at = models.DateField(auto_now_add=True)
    payment_status = models.CharField(
        max_length=1, choices=PAYMENT_STATUS_CHOICES, default=PAYMENT_STATUS_PENDING)
    # Implement a 1-to-many relationship between Customer & Order
    # A customer can have multiple orders
    # if we are accidently delete a customer we do not delete orders
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)


class OrderItem(models.Model):
    # Implement a 1-to-many relationship between Order & Item
    # An Order can have multiple Items
    order = models.ForeignKey(Order, on_delete=models.PROTECT)
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT, related_name='orderitems')
    quantity = models.PositiveSmallIntegerField()
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)


# Implement a 1-to-many relationship between Cart & Item
class ShoppingCart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)


class ShoppingCartItem(models.Model):
    # if we are delete a cart we should delete the items automatically
    shopping_cart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()


# Implement a 1-to-many relationship between Customer & Address
# Note that a customer should exist before creating an address
# with this Implementation a customer can have more than one address
class Address(models.Model):
    street = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    zip = models.CharField(max_length=25, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

fyardstore2/store/views.py
from django.db.models.aggregates import Count
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.parsers import JSONParser
from .models import Product, Collection
from .serializers import CollectionSerializer, ProductSerializer
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView

class homepage(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'store/index.html'

    def get(self, request):
        queryset = Product.objects.all().order_by('id')
        return Response({'products': queryset})


@api_view(['GET', 'POST'])
def product_list(request):
    if request.method == 'GET':
        queryset = Product.objects.select_related('collection').all()
        store_serializer = ProductSerializer(
            queryset, many=True, context={'request': request})
        return Response(store_serializer.data)

    elif request.method == 'POST':
        # This where deserialization happends
        store_serializer = ProductSerializer(data=request.data)
        store_serializer.is_valid(raise_exception=True)
        store_serializer.save()
        return Response(store_serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET', 'PUT', 'DELETE'])
def product_detail(request, id):
    product = get_object_or_404(Product, pk=id)  # get product by id
    if request.method == 'GET':
        # create a serializer and give it this product object
        store_serializer = ProductSerializer(product)
        return Response(store_serializer.data)
    elif request.method == 'PUT':
        # This where deserialization happends
        store_serializer = ProductSerializer(product, data=request.data)
        store_serializer.is_valid(raise_exception=True)
        store_serializer.save()
        # Te RESTful convention is to return the product that was created/update
        return Response(store_serializer.data)
    elif request.method == 'DELETE':
        if product.orderitems.count() > 0:
            return Response(
                {'error': 'Product cannot be deleted'},
                status=status.HTTP_405_METHOD_NOT_ALLOWED
            )
        product.delete()
        return Response({'message': 'Product successfully deleted'})
        # return Response(status=status.HTTP_204_NO_CONTENT)


# Creating the collection endpoint
@api_view(['GET', 'POST'])
def collection_list(request):
    if request.method == 'GET':
        queryset = Collection.objects.annotate(products_count=Count('products')).all()
        store_serializer = CollectionSerializer(queryset, many=True)
        return Response(store_serializer.data)
    elif request.method == 'POST':
        store_serializer = CollectionSerializer(data=request.data)
        store_serializer.is_valid(raise_exception=True)
        store_serializer.save()
        return Response(store_serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET', 'PUT', 'DELETE'])
def collection_detail(request, pk):
    collection = get_object_or_404(
        Collection.objects.annotate(
            products_count = Count('products')), pk=pk)

    if request.method == 'GET':
        store_serializer = CollectionSerializer(collection)
        return Response(store_serializer.data)
    elif request.method == 'PUT':
        store_serializer = CollectionSerializer(collection, data=request.data)
        store_serializer.is_valid(raise_exception=True)
        store_serializer.save()
        return Response(store_serializer.data)
    elif request.method == 'DELETE':
        if collection.products.count() > 0:
            return Response({'error': 'Collection cannot be deleted'})
        collection.delete()
        return Response({'message': 'Collection deleted successfully'})
        # return Response(status=status.HTTP_204_NO_CONTENT)

fyardstore2/store/templates/store/base.html
{% load static %} {% load livereload_tags %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
 
  </head>
  <body>

    <div>{% block content %}{% endblock content %}</div>
    

    {% block jsfiles %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    {% endblock jsfiles %} {% livereload_script %}
  </body>
</html>

fyardstore2/store/templates/store/index.html
{% extends "store/base.html" %} {% load static %}{% block title %} Products List
{% endblock%} {% block content%}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
        <div class="col">
            <div>
                <p class="d-inline p-3 text-uppercase font-monospace fw-bold fs-4 pt-3 text-white">Our Product List</p>
                <a href="{% url 'homepage:home' %}" class="btn btn-warning d-inline p-3">Back Home</a>
            </div>
        </div>
    </div>
    <div class="row d-flex row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for product in products %}
        <div class="cols-6">
            <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                <div class="card-header">Product #{{ product.id }}:</div>
                <div class="card-body">
                    <h5 class="card-title fs-5">{{ product.title }}: ${{ product.unit_price }}</h5>
                    <p class="card-text fs-6">{{ product.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %} {% block jsfiles %} {% endblock jsfiles %}

fyardstore2/store/templates/store/product_list.html
{% extends "store/base.html" %} {% load static %}{% block title %} Products List
{% endblock%} {% block content%}
  <h1>Products List</h1>
  <ul>
    {% for product in products %}
    <li>{{ product.title }} - {{ product.unit_price }}</li>
    {% endfor %}
  </ul>
</body>

{% endblock %} {% block jsfiles %} {% endblock jsfiles %}