fyardstore2/fyardstore/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Fyardstore Admin'
admin.site.index_title = 'Admin Pannel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('main/', include('main.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
]

fyardstore2/main/urls.py
# from urllib.parse import urlparse
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='home'),
]

fyardstore2/store/urls.py
from django.urls import path, include
from . import views

app_name = 'store'

# URLConf
urlpatterns = [
	path('', views.homepage.as_view(), name='home'),
	path('products/', views.product_list),
	path('products/<int:id>/', views.product_detail),
	path('collections/', views.collection_list),
	path('collections/<int:pk>/', views.collection_detail, name='collection-detail')
]

fyardstore2/main/models.py
from django.db import models

# Create your models here.

fyardstore2/main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

fyardstore2/main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Shopping 5 Stars</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
 
</head>
<body>
    <div class="container">
        <div>
            <img src="{% static 'main/images/main_logo.png' %}" class="logo-image pt-4 max-width-100">
            <p>Welcome to Yardley Fashion shop</p>
        </div>
        <a href="{% url 'store:home' %}" class="btn btn-success">See our products</a>
    </div>
</body>
</html>